CREATE TABLE IF NOT EXISTS MKS_USERS (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(10) NOT NULL DEFAULT "NORMAL"
);

CREATE TABLE IF NOT EXISTS MKS_MOVIE (
    id VARCHAR(255) PRIMARY KEY,
    title VARCHAR(80) NOT NULL,
    description VARCHAR(255),
    duration_in_minutes INT NOT NULL,
    year_of_release INT NOT NULL
);

CREATE TABLE IF NOT EXISTS MKS_FAVORITE_MOVIE (
    id VARCHAR(255) PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    movie_id VARCHAR(255) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES MKS_USERS(id),
    FOREIGN KEY (movie_id) REFERENCES MKS_MOVIE(id)
);

