###
POST http://localhost:3000/user/signup
Content-Type: application/json

{
  "name": "test",
  "email": "test@email.com",
  "password": "1234567",
  "role": "ADMIN"
}

###
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "1234567"
}